version: '2'

services:
  wp:
    image: wordpress:latest
    domainname: ${DOMAIN}
    ports:
      - '80:80'
    volumes:
      - ./config/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
      - ./wp-app:/var/www/html
      - ./theme-base/:/var/www/html/wp-content/themes/theme-base
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: '${DB_NAME}'
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: '${DB_ROOT_PASSWORD}'
    depends_on:
      - db

  wpcli:
    image: wordpress:cli
    volumes:
      - ./config/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
      - ./wp-app:/var/www/html
    depends_on:
      - db
      - wp

  db:
    image: mariadb
    ports:
      - '3306:3306'
    environment:
      MARIADB_DATABASE: '${DB_NAME}'
      MARIADB_ROOT_PASSWORD: '${DB_ROOT_PASSWORD}'
    volumes:
      - ./wp-data:/docker-entrypoint-initdb.d
      - db:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - ${LOCAL_PORT_PHPMYADMIN}:80
    links:
      - db:db

volumes:
  db:
